name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.123.200.110 << 'EOF'
            set -e  # Quitter en cas d'erreur
            cd /var/www/html/ProjetWeb
            git pull origin main
            composer install --no-dev --optimize-autoloader
            sudo php bin/console cache:clear --env=prod
          EOF
